name: "deploy code on EC2 instance"

on:
    workflow_dispatch 


jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: "install node"
              uses: actions/setup-node@v4
              

            - name : "checkout code"
              uses: actions/checkout@v2

            - name: "install dependencies"
              uses: npm install -g 

            - name: "pm2 install"
              uses: pm2 install -g pm2
                                  
            - name: "deploy to aws"
              run : 
                    pm2 start src/app.js