name: "deploy code on EC2 instance"

on:
    workflow_dispatch 


jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: "install node"
              run: |
                    actions/setup-node@v4
                    
            - name : "checkout code"
              uses: actions/checkout@v2

            - name: "install dependencies"
              run: |
                     npm install 
                     pm2 install
                    
            - name: "deploy to aws"
              run : 
                    pm2 start src/app.js