name: "Deploy code on EC2 instance"

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Install Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or any version you want

      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        uses: npm install

      - name: "Install PM2 globally"
        uses: npm install -g pm2
          

      - name: "Start app with PM2"
        run: |
          pm2 start src/app.js --name freshfood-app
